### ISSUE TITLE
readHeader.R: EOF within quoted string. 

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/tantalus#1]
Some summary files are giving an error when the `readHeader` function is called regarding EOF within quoted string. Doesn't seem to be a huge issue but should figure out what's going on and fix it.

Tracked down to `readHeader.R` Line 11.

```
> readHeader( sumFile = "data/test/SRR5447135.summary")
[1] "data/test/SRR5447135.summary"
         sra genome         date
1 SRR5447135 cov3ma 200530-02:48
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
```

While some other summary files do not give an error:

```
> readHeader(sumFile = "data/test/SRR3458562.summary")
[1] "data/test/SRR3458562.summary"
         sra genome         date
1 SRR3458562 cov3ma 200530-03:31
> sumFiles[2]
```

---

This also applies to `readHits` function, either with family = T or family = F.

**Comment by ababaian** [comment]
I bring this up because in the `SERRATUS` objects, there are row entries with NA in all fields, and I believe this is most likely arising with EOF not being parsed correctly, see below.

![Screenshot from 2020-06-02 21-37-04](https://user-images.githubusercontent.com/9220907/83596343-f3d65500-a553-11ea-9450-be7d8bed0707.png)

**Comment by fransilvion** [comment]
Now it should be fixed
