### ISSUE TITLE
how to obtain the scientific_name of sra runs using tantalus

### ISSUE THREAD

**Issue by holypeggy** [serratus-bio/tantalus#11]
hi,
I want to used tantalus extract the scientifc_name (the sequencing organisms) with a group of sra numbers. 
I can obtain the all 22 tables lised in the SQL, but not one contains the related informaion. 
I am appreciate if you can provide some help. 
Thanks.

**Comment by ababaian** [comment]
The `srarun` table has the main SRA meta-data fields, including `scientific_name`. Is that sufficient?

**Comment by holypeggy** [comment]
Thanks for your reply.
i can obtain cov.nt.sra file with the example script but not for the srarun. Please provide some tips. 
sra.accessions <- c("SRR10144611", "SRR6906297", "SRR6906298",  "SRR6906299",
                    "SRR6906300", "SRR6906303", "SRR3229029", "SRR3229077", 
                    "SRR3229078", "SRR3229081")
srarun <- readDfSQL(con,
                        table = "srarun",
                        family = "Coronaviridae",
                        sras = sra.accessions,
                        dataframe = T)

**Comment by ababaian** [comment]
What is the output of this? Or what error message is being given?

**Comment by holypeggy** [comment]
> srarun <- readDfSQL(con,
+                     table = "srarun",
+                     family = "Coronaviridae",
+                     sras = sra.accessions,
+                     dataframe = T)
�!�) in postgresqlExecStatement(conn, statement, ...) : RS-DBI driver: (

**Comment by holypeggy** [comment]
�!�) in postgresqlExecStatement(conn, statement, ...) : RS-DBI driver: ( 

in win10 platform

**Comment by holypeggy** [comment]
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: ((nil))

**Comment by ababaian** [comment]
Fixed it, there was a difference between how the `srarun` table was naming the `run_id` column. I've updated the `tantalus` code, just update and this will work:
```
# Update Tantatlus
install_github("serratus-bio/tantalus")
```

## Selecting a sub-set of `runs` from `sraruns`
```
library("tantalus")
library("dbplyr")
library("RPostgres") 

# Connect to Serratus Database
drv <- DBI::dbDriver("PostgreSQL")
con <- DBI::dbConnect(drv,
                      user="public_reader", 
                      password="serratus",
                      host="serratus-aurora-20210406.cluster-ro-ccz9y6yshbls.us-east-1.rds.amazonaws.com",
                      port=5432, 
                      dbname="summary")

sra.accessions <- c("SRR10144611", "SRR6906297", "SRR6906298", "SRR6906299",
                    "SRR6906300", "SRR6906303", "SRR3229029", "SRR3229077",
                    "SRR3229078", "SRR3229081")

srarun <- readDfSQL(con,
                    table = "srarun",
                    sras = sra.accessions,
                    dataframe = T)
```

**Comment by holypeggy** [comment]
Nice. It works. thanks.Tong
