### ISSUE TITLE
getSummaryFiles doesn't authenticate

### ISSUE THREAD

**Issue by cjcarlson** [serratus-bio/tantalus#4]
```
sras <- c("SRR5447167")
sras
[1] "SRR5447167"
serr <- getSummaryFiles(sras, 's3://lovelywater/summary/', "C:/Users/cjcar/Desktop/sra")
[1] "aws s3 cp s3://lovelywater/summary/SRR5447167.summary C:/Users/cjcar/Desktop/sra/"
fatal error: Unable to locate credentials
```

**Comment by ababaian** [comment]
[Link to the other thread](https://github.com/serratus-bio/tantalus/issues/3#issuecomment-776847094)

**Comment by victorlin** [comment]
@cjcarlson if this is blocking your work, another (shameless plug) option is [serratus-summary-api](https://github.com/serratus-bio/serratus-summary-api) which was just built and is being used on https://dev.serratus.io/. Still working on some more functionality+documentation, but it’s serving the latest Serratus data. Eventually `tantalus` will be updated to use the same database.

**Comment by cjcarlson** [comment]
Thanks, but I am really hoping to use the R package if we can get this to work :)

**Comment by ababaian** [comment]
I can't reproduce this but can you try this version of the `getSummary` function for me:

```
getSummary <- function( s3_path, local_path ){

  systemCMD <- paste0("aws s3 sync --no-sign-request ",
                      s3_path,
                      '/summary/ ',
                      local_path,"/")
}
```

And to confirm try this on your system command-line

```
aws s3 sync --no-sign-request $S3_SUMMARY $LOCAL_PATH
```

**Comment by cjcarlson** [comment]
So, this executes completely correctly from command line:

`aws s3 cp s3://lovelywater/summary/SRR5447167.summary C:/Users/cjcar/Desktop/sra/`

This throws the "fatal error: Unable to locate credentials" error from RStudio:

`system("aws s3 cp s3://lovelywater/summary/SRR5447167.summary C:/Users/cjcar/Desktop/sra")`

Not sure why those two things are different - they shouldn't be

**Comment by ababaian** [comment]
Did you try with `--no-sign-request` the data is available without credentials. I'll add a fall-back in case of failure to use `wget` but I don't have time right now to do this properly. In the meanwhile I'd suggest use this function:

```
getSummary <- function(  sra ){
  systemCMD <- paste0("wget https://lovelywater.s3.amazonaws.com/summary/", sra, ".summary ",
                                       local_path,"/")
}
```

Please do leave the issue open until it's resolved properly.

**Comment by cjcarlson** [comment]
Hey, just tried something different - loaded the package `aws.s3` first, then manually set Sys.setenv() [like this](https://www.gormanalysis.com/blog/connecting-to-aws-s3-with-r/) and we're golden - worked like a charm. Is that standard practice and I just missed it in the docs? Might be worth flagging it in a vignette or similar.

**Comment by ababaian** [comment]
That's an easy fix then, I never had this issue but I can throw it into the docs :+1:

**Comment by ababaian** [comment]
One note though, be sure to use `us-east-1` if you're working with SRA/Serratus data. This will prevent 'egress' charges from incurring from cross-region filetransfer. You'll probably not run into this issue for a while but it saves us some $$$

**Comment by cjcarlson** [comment]
Sounds good. However, I do unfortunately have a new issue, but I'll close and reopen.
