### ISSUE TITLE
getSummaryFiles issue

### ISSUE THREAD

**Issue by cjcarlson** [serratus-bio/tantalus#5]
A new problem emerges:

```
> serr <- getSummaryFiles(sras, local_path = "C:/Users/cjcar/Desktop/sra")
[1] "aws s3 cp s3://lovelywater/summary/SRR5447167.summary C:/Users/cjcar/Desktop/sra/"
download: s3://lovelywater/summary/SRR5447167.summary to Desktop\sra\SRR5447167.summary
Error in data.frame(sra = sra, genome = genome, date = date, stringsAsFactors = F) : 
  arguments imply differing number of rows: 1, 0
```

Just so you know - this error comes up if your scripts to run serratus are saved locally in the same directory as the .summary files themselves, because it's not only pulling .summary files, it pulls everything. So it identifies your .R script as a summary file it wants to try to read.

**Comment by ababaian** [comment]
Thanks, fixed by adding a regex  for only `.summary` files to be returned. Thanks for being a good beta-tester, keep em coming.

**Comment by cjcarlson** [comment]
Having fun with it!
