### ISSUE TITLE
Problem to generate the connection to the DB

### ISSUE THREAD

**Issue by anachshon** [serratus-bio/tantalus#9]
Hi,

I managed to install on our Linux cluster the tantalus package and the RPostgreSQL packages, but did not manage to pass the line

con <- DBI::Connect( ... 

from the readme file. The error I am getting is shown below.
This is the case for both R versions 3.6.0 and 4.1.0.

Also on my mac laptop, R version 4.1.0 I am getting (different) error on the same line.

Thanks,
aharon.

 *** caught segfault ***
address 0xffffffff, cause 'memory not mapped'

Traceback:
 1: postgresqlNewConnection(drv, ...)
 2: DBI::dbConnect(drv, user = "public_reader", password = "serratus",     host = "serratus-aurora-20210310.cluster-ro-ccz9y6yshbls.us-east-1.rds.amazonaws.com",     port = 5432, dbname = "summary")
 3: DBI::dbConnect(drv, user = "public_reader", password = "serratus",     host = "serratus-aurora-20210310.cluster-ro-ccz9y6yshbls.us-east-1.rds.amazonaws.com",     port = 5432, dbname = "summary")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by ababaian** [comment]
I really don't know why it would segfault, but make sure the script has the most recent version of the login credentials as shown on [this page](https://github.com/ababaian/serratus/wiki/SQL-Schema).

**Comment by anachshon** [comment]
I just came back to this page to write that the problem was solved after using the right hostname and saw your response :-)

Thanks a lot for the very prompt response.

It will be nice also in the readme here (in the example code) to include the link to the updated details.

It is great / encouraging to know that someone is responding on the other side :-)

Thanks.

**Comment by ababaian** [comment]
@fransilvion can you update README/script plz

**Comment by fransilvion** [comment]
Done

**Comment by eul2021** [comment]
Hi, I've tantalus installed on a cluster server Rstudio, but cannot establish connection. The session restarts with "Error: Error occurred during transmission".   Thank you for any hints on how to debug this.

con <- DBI::dbConnect(drv,
+                       user="public_reader", 
+                       password="serratus",
+                       host="serratus-aurora-20210406.cluster-ro-ccz9y6yshbls.us-east-1.rds.amazonaws.com",
+                       port=5432, 
+                       dbname="summary")
Error: Error occurred during transmission
